### ISSUE TITLE
[Bug] Configuration command ('/haseltweaks') not working or displaying in Plugin Installer UI

### ISSUE THREAD

**Issue by aether-afk** [Haselnussbomber/HaselTweaks#108]
I am observing a bug where I'm unable to open the configuration window through '/haseltweaks'. The issue resolves itself when I manually disable and reenable the plugin, but will reoccur on game exit and relaunch. I can observe that the tweaks themselves are still running, as the Gear Set Grid window still opens.

It is also not listed in the Plugin Installer when this issue is observed:

![image](https://github.com/Haselnussbomber/HaselTweaks/assets/173726340/b11cab7e-fb78-4d7a-880c-098468f4e59a)

**Comment by Haselnussbomber** [comment]
Heya, I found some issues with tweaks not fully cleaning themselves up when the plugin is unloaded.
I *just* released an update to hopefully fix this.
Please update (to [v24.0.2](https://github.com/Haselnussbomber/HaselTweaks/releases/tag/v24.0.2)), restart the game and see if it works again!

**Comment by aether-afk** [comment]
Still observing the same error unfortunately:

![image](https://github.com/Haselnussbomber/HaselTweaks/assets/173726340/2400f419-3d57-459a-b8d3-a51736a86b34)

I have a trace, let me know if you can use anything else:

2024-06-24 12:44:35.094 -07:00 [ERR] Unobserved exception in Task.
System.AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. (Object reference not set to an instance of an object.)
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at HaselTweaks.Windows.PluginWindow..ctor(IWindowManager windowManager, DalamudPluginInterface pluginInterface, TextService textService, IPluginLog pluginLog, ICommandManager commandManager, TweakManager tweakManager, IEnumerable`1 tweaks) in /_/HaselTweaks/Windows/PluginWindow.cs:line 64
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeWithManyArgs(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.CreateServiceAccessor(ServiceIdentifier serviceIdentifier)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(ServiceIdentifier serviceIdentifier, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at HaselTweaks.Plugin.<>c.<.ctor>b__0_1() in /_/HaselTweaks/Plugin.cs:line 95
   at Dalamud.Game.Framework.<>c__DisplayClass67_0.<RunOnTick>b__0(Task[] _) in C:\goatsoft\companysecrets\dalamud\Game\Framework.cs:line 261
   at System.Threading.Tasks.TaskFactory`1.<>c.<ContinueWhenAllImpl>b__57_1(Task`1 completedTasks, Object state)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
   --- End of inner exception stack trace ---

**Comment by Haselnussbomber** [comment]
Thanks, that was helpful!

I released another update which should fix it. Please update to [v24.0.2](https://github.com/Haselnussbomber/HaselTweaks/releases/tag/v24.0.2). 🙂

If you're interested in the reason why this was happening:
In the plugin manifest I'm telling Dalamud that it can load the plugin early, before ImGui is set up, because I wasn't expecting any code to access ImGui functions.
Due to my rework I'm now creating the configuration window when the plugin loads and in its constructor it calculates the width of the window using ImGui functions to get the paddings. This will fail, since ImGui isn't ready.

**Comment by ivalith** [comment]
Wasn't sure whether to reply to this issue or create a new one but I've recently started experiencing this recently for the first time after never experiencing it previously. I also cannot use a command to access the haseltweaks setting or access it through the plugin installer window unless I disable and re-enable the plugin. To clarify as well, the plugin also doesn't seem to function until disabling/re-enabling (I noticed this because I use 'background music keybind' often and noticed it not working recently unless I disable/re-enable).

Attached screenshots of the installer window reflecting the /haseltweaks command not being available and then appearing afterward. 

![Image](https://github.com/user-attachments/assets/dfeb051f-3c97-4f51-9028-c2bfb1e50f47)

![Image](https://github.com/user-attachments/assets/048fac1d-2a47-4aee-ae87-adc9c7d7a494)

**Comment by Haselnussbomber** [comment]
Last update should've fixed that, but I forgot to change the version in the plugin manifest so Dalamud didn't copy the files, I think.
I just pushed [v32.0.2](https://github.com/Haselnussbomber/HaselTweaks/releases/tag/v32.0.2). Please update and see if that works (preferably after a restart of the game, since it affects first load)! 😅

**Comment by ivalith** [comment]
Didn't seem to do the trick. Made sure to update to 32.0.2 just now, confirmed plugin worked and then restarted and the issue still occurred with the same fix working. (Appreciate the very quick attention to this however!)

**Comment by Haselnussbomber** [comment]
I honestly don't know what it could be. Is there any exception in your dalamud log (at `%APPDATA%\XIVLauncher\dalamud.log`)?

**Comment by ivalith** [comment]
(No worries and no rush with this of course I just appreciate you giving it your attention!) I searched through my log to find any errors and warnings I could look into and the only thing that seems potentially related was the following: 

```
00:57:44.795 | ERR | Unobserved exception in Task.
	System.AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. (Scene is not yet ready.)
	 ---> System.InvalidOperationException: Scene is not yet ready.
	   at Dalamud.Interface.UiBuilder.get_DefaultFontHandle() in /_/Dalamud/Interface/UiBuilder.cs:line 359
	   at HaselCommon.Services.GlobalScaleObserver..ctor(IDalamudPluginInterface pluginInterface) in /_/HaselCommon/Services/GlobalScaleObserver.cs:line 16
	   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
	   at System.Reflection.MethodBaseInvoker.InvokeDirectByRefWithFewArgs(Object obj, Span`1 copyOfArgs, BindingFlags invokeAttr)
	   at System.Reflection.MethodBaseInvoker.InvokeWithOneArg(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
	   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
	   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
	   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
	   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
	   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
	   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
	   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
	   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
	   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
	   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
	   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
	   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
	   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
	   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitIEnumerable(IEnumerableCallSite enumerableCallSite, RuntimeResolverContext context)
	   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
	   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
	   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
	   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
	   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
	   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
	   at Microsoft.Extensions.DependencyInjection.ServiceProvider.CreateServiceAccessor(ServiceIdentifier serviceIdentifier)
	   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
	   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(ServiceIdentifier serviceIdentifier, ServiceProviderEngineScope serviceProviderEngineScope)
	   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
	   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
	   at HaselTweaks.Plugin.<.ctor>b__1_0() in /_/HaselTweaks/Plugin.cs:line 48
	   at Dalamud.Game.Framework.<>c__DisplayClass64_0.<RunOnTick>b__0(Task[] _) in /_/Dalamud/Game/Framework.cs:line 246
	   at System.Threading.Tasks.TaskFactory`1.<>c.<ContinueWhenAllImpl>b__57_1(Task`1 completedTasks, Object state)
	   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
	   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
	--- End of stack trace from previous location ---
	   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
	   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
	   --- End of inner exception stack trace ---
```

**Comment by Haselnussbomber** [comment]
I see, the related issue is #144. Seems like I need to solve that differently.

**Comment by ivalith** [comment]
Just wanted to confirm that 32.0.3 did in fact fix this issue, thanks very much!
