### ISSUE TITLE
Enhanced Login/Logout crashes on login

### ISSUE THREAD

**Issue by sersorrel** [Haselnussbomber/HaselTweaks#136]
Hitting "OK" on the login dialog crashes the game.

![image](https://github.com/user-attachments/assets/d2b69ff7-b54d-4074-a560-a0f0560538ed)

This happens even with none of the module options enabled.

![image](https://github.com/user-attachments/assets/3b3fcba3-8607-4b3a-88b1-5533b09cb80c)

The dump looks utterly bizarre:

```
Unhandled exception: 0xe0434352 in 64-bit code (0x0000007b0133ee).
Register dump:
 rip:000000007b0133ee rsp:000000000011e090 rbp:000000000011e440 eflags:00000206 (   - --  I   - -P- )
 rax:000000000011e0d0 rbx:00000003a684c9a8 rcx:000000000011e0b0 rdx:0000000000000001
 rsi:000000000011e250 rdi:000000000011e0f8  r8:0000000000000005  r9:000000000011e228 r10:0000000000000005
 r11:000000000011e168 r12:0000000000004000 r13:0000000011817e00 r14:0000000000000001 r15:00000000e0434352
Stack dump:
0x0000000011e090:  000000000011e0b0 000000000326a59e
0x0000000011e0a0:  0000000000396be0 00000003a684c908
0x0000000011e0b0:  00000001e0434352 0000000000000000
0x0000000011e0c0:  000000007b0133ee 0000000300000005
0x0000000011e0d0:  ffffffff80131502 0000000000000000
0x0000000011e0e0:  0000000000000000 0000000000000000
0x0000000011e0f0:  0000000003170000 00000000821f6fd3
0x0000000011e100:  000000036b1a8100 000000000011e3f0
0x0000000011e110:  000000000011e428 000000000011e3f4
0x0000000011e120:  000000000011e1e0 00000003a684c908
0x0000000011e130:  0000000000000000 0000000000000000
0x0000000011e140:  0000000000396be0 000000000011e2e8
Backtrace:
=>0 0x0000007b0133ee in kernelbase (+0x133ee) (0x0000000011e440)
  1 0x0000000326a3f7 in coreclr (+0xfa3f7) (0x0000000011e440)
  2 0x00000003269b49 in coreclr (+0xf9b49) (0x0000000011e440)
0x0000007b0133ee kernelbase+0x133ee: nop
```

There's nothing in dalamud.log when this happens.

**Comment by Haselnussbomber** [comment]
I can't reproduce this (otherwise I would've fixed it already), but I found out that the "Preload territory when queued" function was always active.
I've released [v28.0.2](https://github.com/Haselnussbomber/HaselTweaks/releases/tag/v28.0.2) that respects the enable state.
Maybe now it works?

**Comment by sersorrel** [comment]
Still broken unfortunately. I can try compiling the plugin myself to add some debug logging, but it will be a few days before I get time probably.

**Comment by Haselnussbomber** [comment]
Did you disable all other plugins? AgentLobby wasn't updated and still isn't in Dalamud.
I provide my own ClientStructs and all the parts I need for this whole tweak are still correct.

**Comment by sersorrel** [comment]
> And maybe tried to turn the whole tweak off?

yes, it works fine with this specific tweak disabled.

**Comment by Haselnussbomber** [comment]
I just changed it so it doesn't even hook `AgentLobby.OpenLoginWaitDialog` when the option "Preload territory when queued" isn't enabled. Not sure if that helps.

Waitingway also seems to be causing a lot of crashes, according to the Dalamud Discord. Sadly it uses its own AgentLobby struct at the moment, so that a Dalamud update alone wouldn't be enough.

**Comment by sersorrel** [comment]
I was about to say I think that fixed it, but the crash is no longer happening at all, even with the module (and territory-preload) enabled >.> I do have Waitingway installed, so maybe that was related after all.
