### ISSUE TITLE
Spurious portrait warning when glamours are unavailable on current job

### ISSUE THREAD

**Issue by Zumurrud** [Haselnussbomber/HaselTweaks#79]
My tank gear has PLD-specific glamours applied, so on WAR those items have their original appearance.  My WAR portrait is saved with the items' original appearance, and the portrait works when tested.

Despite this, every time I switch to the WAR gearset, HaselTweaks warns that "Current appearance and/or gear does not match that shown in portrait".

**Comment by Haselnussbomber** [comment]
I have to think about it.
Are you using glamour plates on either of those gear sets? I assume not.

**Comment by Haselnussbomber** [comment]
I have released [v20.0.1](https://github.com/Haselnussbomber/HaselTweaks/releases/tag/v20.0.1) with a possible fix. Please check it out! 🙂

**Comment by Zumurrud** [comment]
Hello!  Thank you for looking at this so quickly.

Unfortunately, this does not fix my problem, or at least not entirely.  After a little bit of testing, it seems to be related to dyes, and specifically I suspect it stems from the fact that dyes are ignored when the glamour is unavailable.

When I recreate exactly the conditions mentioned in the issue (glamour unavailable, but no dye), then no warning is generated.  If the unavailable glamour is also dyed, then I still get HaselTweak's warning, but the portrait works in-game.

**Comment by Haselnussbomber** [comment]
Right, I totally forgot about dyes.

I released [v20.0.2](https://github.com/Haselnussbomber/HaselTweaks/releases/tag/v20.0.2), which now ignores dyes when the glamour could not be applied due to class/job restrictions or if the glamour is not dyeable. Seems like this fixed it?

**Comment by Zumurrud** [comment]
Works perfectly for me now.  Thank you!

The portrait helper, market search, and auto-open recipe parts of this plugin have saved me so much aggravation over time.  I love it.
